#!/bin/bash
echo "Begin post_run with $1"
[ -z "$1" ] && echo "Error, $0 requires 'jdd' as argument"
err=$1.err
cwd=$PWD

[ ! -f $err ] && echo "Error in post_run. $err is missing" && exit -1

grep -E "instant-Q|Volume_phase_0|vevap_int|v_cl_test=|instantaneous meso-evaporation =|Instantaneous tcl-evaporation =|theta_app_degree=" \
   $err > short_$err

grep "Volume_phase_0" short_$err | awk '{print $4, $2}' > vap_vol.txt
[ $(wc -l vap_vol.txt| awk '{print $1}') != 0 ] && v0=$(head -n1 vap_vol.txt | awk '{print $2}') || v0=0.
d0=$(python3 -c 'from math import pi; v='$v0'; d=(6*v/pi)**(1./3.); print(d)')
awk '{print $1*1000, '$d0'*($2/'$v0')^(1/3)}' vap_vol.txt > dia_full.txt ; awk 'NR % 100 == 0' dia_full.txt > dia.txt


rm -rf lata/post-ascii.lata*
[ -f lata/post.lata ] && sed "/dom/d" lata/post.lata > lata/post-interf.lata && lata_analyzer lata/post-interf.lata asciiout writelata_convert=lata/post-interf-ascii.lata && echo "Conversion to lata/post-interf-ascii.lata with success"
#grep "time_sommet_tcl=" $err | awk '{print $6*1000, ($4/'$v0')^(1/3)}' > base_dia.txt 
if [ -f lata/post-interf-ascii.lata ] ; then
   echo "Generate interface-position.txt"
   echo "# t    rmin rmax xmax ymax ymin rcl" > interface-position.txt
   for fic in `ls -n lata/post-interf-ascii_post.lata.INTERFACES.0.*[0-9] | awk '{print $NF}'`
   do
      time=$(echo $fic | awk -FFACES. '{print $2}')
      sed '1d;$d' $fic | awk 'NR == 1 { xmax=$1; xcl=$1; ymax=$2; ymin=$2; rmin=sqrt($1*$1+$2*$2) ; rmax=sqrt($1*$1+$2*$2) }
      { r=sqrt($1*$1+$2*$2); if ($1>xmax) xmax=$1; if ($2>ymax) ymax=$2; if ($2<ymin) {ymin=$2; xcl=$1}; if (r>rmax) rmax=r; if (r<rmin) rmin=r; }
      END {printf "%g %g %g %g %g %g %g\n", "'$time'", rmin, rmax, xmax, ymax, ymin, xcl}' >> interface-position.txt
      echo -n "."
   done
   echo ""
   awk '{print $1*1000, $7}' interface-position.txt > base_dia.txt 
fi
