#!/bin/bash
Cases=(VDF_KEPS_STANDARD VDF_KEPS_REALISABLE VEF_KEPS_STANDARD VEF_KEPS_REALISABLE)

for cas in "${Cases[@]}"; do
    cd "../${cas}" || exit

    extrait_coupe Cas KEPS
    extrait_coupe Cas NUT
    extrait_coupe Cas VITESSEX
    extrait_coupe Cas VITESSEY
    extrait_coupe Cas VITESSEZ
    extrait_coupe Cas SOURCES_KEPS
    extrait_coupe Cas DIFF_KEPS
    extrait_coupe Cas CONV_KEPS

    sed 1d Cas_KEPS.coupe | awk '{print $1" "$2}' >tke.dat
    sed 1d Cas_KEPS.coupe | awk '{print $1" "$3}' >eps.dat
    sed 1d Cas_NUT.coupe | awk '{print $1" "$2}' >nut.dat
    sed 1d Cas_VITESSEX.coupe | awk '{print $1" "$2}' >u1.dat
    sed 1d Cas_VITESSEY.coupe | awk '{print $1" "$2}' >u2.dat
    sed 1d Cas_VITESSEZ.coupe | awk '{print $1" "$2}' >u3.dat
    sed 1d Cas_SOURCES_KEPS.coupe | awk '{print $1" "$2}' >source_tke.dat
    sed 1d Cas_SOURCES_KEPS.coupe | awk '{print $1" "$3}' >source_eps.dat
    sed 1d Cas_DIFF_KEPS.coupe | awk '{print $1" "$2}' >diff_tke.dat
    sed 1d Cas_DIFF_KEPS.coupe | awk '{print $1" "$3}' >diff_eps.dat
    sed 1d Cas_CONV_KEPS.coupe | awk '{print $1" "$2}' >conv_tke.dat
    sed 1d Cas_CONV_KEPS.coupe | awk '{print $1" "$3}' >conv_eps.dat

    rm -f *coupe
done

Cases=(VDF_KOMG_STANDARD VEF_KOMG_STANDARD)

for cas in "${Cases[@]}"; do
    cd "../${cas}" || exit

    extrait_coupe Cas KOMEGA
    extrait_coupe Cas NUT
    extrait_coupe Cas VITESSEX
    extrait_coupe Cas VITESSEY
    extrait_coupe Cas VITESSEZ
    extrait_coupe Cas SOURCES_KOMEGA
    extrait_coupe Cas DIFF_KOMEGA
    extrait_coupe Cas CONV_KOMEGA

    sed 1d Cas_KOMEGA.coupe | awk '{print $1" "$2}' >tke.dat
    sed 1d Cas_KOMEGA.coupe | awk '{print $1" "$3}' >omega.dat
    sed 1d Cas_NUT.coupe | awk '{print $1" "$2}' >nut.dat
    sed 1d Cas_VITESSEX.coupe | awk '{print $1" "$2}' >u1.dat
    sed 1d Cas_VITESSEY.coupe | awk '{print $1" "$2}' >u2.dat
    sed 1d Cas_VITESSEZ.coupe | awk '{print $1" "$2}' >u3.dat
    sed 1d Cas_SOURCES_KOMEGA.coupe | awk '{print $1" "$2}' >source_tke.dat
    sed 1d Cas_SOURCES_KOMEGA.coupe | awk '{print $1" "$3}' >source_omega.dat
    sed 1d Cas_DIFF_KOMEGA.coupe | awk '{print $1" "$2}' >diff_tke.dat
    sed 1d Cas_DIFF_KOMEGA.coupe | awk '{print $1" "$3}' >diff_omega.dat
    sed 1d Cas_CONV_KOMEGA.coupe | awk '{print $1" "$2}' >conv_tke.dat
    sed 1d Cas_CONV_KOMEGA.coupe | awk '{print $1" "$3}' >conv_omega.dat

    rm -f *coupe
done
